# Generated by Django 5.1.4 on 2025-02-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flovers',
            new_name='Flowers',
        ),
    ]
