# Generated by Django 5.1.4 on 2025-02-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_rename_flovers_flowers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowers',
            options={'ordering': ['time_create']},
        ),
        migrations.AddField(
            model_name='flowers',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='flowers',
            index=models.Index(fields=['time_create'], name='flowers_flo_time_cr_a254e9_idx'),
        ),
    ]
