# Generated by Django 5.1.4 on 2025-02-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_alter_flowers_options_flowers_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
