# Generated by Django 5.1.4 on 2025-03-15 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_category_alter_flowers_is_published_flowers_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='flowers.category'),
            preserve_default=False,
        ),
    ]
